import os
basedir = os.path.abspath(os.path.dirname(__file__))

class Config(object):
    GOOGLEMAPSAPI_KEY = "AIzaSyBb3AvxR3cAzQny4omOw5Vze5BgrywRp-A"
    FOURSQUARE_CLIENT_ID = "WGNW01DD2EDMXMDM3HDDTN2WNAOV2TNUFKJ4P5WCP11BNO5Z"
    FOURSQUARE_CLIENT_SECRET = "EW2B5DEQWQZQ4JVU1MSB5ULKREZ1E1CZ1ZM3JOPUOK4THMDM"
    MAPBOX_ACCESS_KEY = "pk.eyJ1IjoibGhvY2hlbnlhbmciLCJhIjoiY2p1OTVkcHJhMGRyZTQ0cGU1NHhmdGd3dCJ9.FzGBsgjrz6pvXqlZTxROuw"
